IS_LOCAL=true
STORE_PASSWORD=nextup!3
KEY_ALIAS=Nextuple Inc
KEY_PASSWORD=nextup!3
APP_CENTER_KEY=1234567890
GOAT_API_LOCAL=http://10.0.0.21:8080/
GOAT_API_DEV=http://10.0.0.21:8080/
GOAT_API_STAGE=http://10.0.0.21:8080/
GOAT_API_PROD=http://10.0.0.21:8080/