IS_LOCAL=true
STORE_PASSWORD=nextup!3
KEY_ALIAS=Nextuple Inc
KEY_PASSWORD=nextup!3
APP_CENTER_KEY=1234567890
GOAT_API_LOCAL=http://10.0.2.2:3658/m1/472566-0-default/
GOAT_API_DEV=https://internal-demo.nextuple.com/services/bff/
GOAT_API_STAGE=http://10.0.2.2:3658/m1/366927-0-default/
GOAT_API_PROD=http://10.0.2.2:3658/m1/366927-0-default/