IS_LOCAL=true
STORE_PASSWORD=nextup!3
KEY_ALIAS=Nextuple Inc
KEY_PASSWORD=nextup!3
APP_CENTER_KEY=1234567890
GOAT_API_URL_LOCAL=http://10.0.0.14:8080/
GOAT_API_URL_DEV=https://internal-dev.nextuple.com/services/bff/
GOAT_API_URL_DEMO=https://internal-demo.nextuple.com/services/bff/
GOAT_API_URL_PROD=https://internal.nextuple.com/services/bff/