import com.nextuple.nsf.UtilKt as Util

plugins {
	id 'com.android.application'
	id 'com.google.dagger.hilt.android'
	id 'com.google.devtools.ksp'
	id 'org.jetbrains.kotlin.android'
	id 'maven-publish'
	id 'jacoco'
	id 'org.sonarqube' version '4.4.1.3373'
	id 'shot'
	id 'com.google.protobuf'
	id 'com.google.gms.google-services'
}

sonarqube {
	properties {
		property "sonar.projectName", "nss-app-ui"
		property "sonar.projectKey", "nsf-app-ui"
		property "sonar.organization", "nextuple"
		property "sonar.coverage.exclusions", ["**/ui/*"]
	}
}

def APK_VERSION = Util.getVersion()
def GIT_HASH = Util.getEnv('GIT_HASH')

def STORE_FILE = file("$project.rootDir/nextuple-keystore.jks")

def STORE_PASSWORD = Util.getEnv('STORE_PASSWORD')
def KEY_ALIAS = Util.getEnv('KEY_ALIAS')
def KEY_PASSWORD = Util.getEnv('KEY_PASSWORD')

def USER_ID = Util.getEnv('USER')

def GOAT_API_URL_LOCAL = Util.getEnv('GOAT_API_URL_LOCAL')
def GOAT_API_URL_DEV = Util.getEnv('GOAT_API_URL_DEV')
def GOAT_API_URL_DEMO = Util.getEnv('GOAT_API_URL_DEMO')
def GOAT_API_URL_PROD = Util.getEnv('GOAT_API_URL_PROD')

android {
	namespace 'com.nextuple.nsf'
	compileSdk 34

	signingConfigs {
		nsf {
			storeFile STORE_FILE
			storePassword STORE_PASSWORD
			keyAlias KEY_ALIAS
			keyPassword KEY_PASSWORD
		}
	}

	defaultConfig {
		applicationId "com.nextuple.nsf"
		minSdk 30
		versionCode 1
		versionName APK_VERSION
		signingConfig signingConfigs.nsf

		testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
		testInstrumentationRunner "com.karumi.shot.ShotTestRunner"

		vectorDrawables {
			useSupportLibrary true
		}

		multiDexEnabled true

		buildConfigField "String", "APP_VERSION", "\"$APK_VERSION\""

		// DEBUG-only
		buildConfigField "String", "USER_ID", "\"$USER_ID\""
	}

	buildTypes {
		debug {
			signingConfig signingConfigs.nsf
			enableUnitTestCoverage true
			enableAndroidTestCoverage true
		}
		release {
			signingConfig signingConfigs.nsf

			minifyEnabled false
			proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

			debuggable false
			enableUnitTestCoverage false
			enableAndroidTestCoverage false
		}
	}

	flavorDimensions = ['default']

	productFlavors {
		prod {
			applicationId "com.nextuple.nsf"

			buildConfigField "String", "GOAT_API_URL", "\"$GOAT_API_URL_PROD\""

			// DEBUG-only
			buildConfigField "Boolean", "AUTO_FILL_USER_ID", "false"
			buildConfigField "Boolean", "BYPASS_PRINTER", "false"
		}

		demo {
			applicationId "com.nextuple.nsf.dev"

			buildConfigField "String", "GOAT_API_URL", "\"$GOAT_API_URL_DEMO\""

			// DEBUG-only
			buildConfigField "Boolean", "AUTO_FILL_USER_ID", "false"
			buildConfigField "Boolean", "BYPASS_PRINTER", "false"
		}

		dev {
			applicationId "com.nextuple.nsf.dev"

			buildConfigField "String", "GOAT_API_URL", "\"$GOAT_API_URL_DEV\""

			// DEBUG-only
			buildConfigField "Boolean", "AUTO_FILL_USER_ID", "false"
			buildConfigField "Boolean", "BYPASS_PRINTER", "false"
		}

		local {
			applicationId "com.nextuple.nsf.local"

			buildConfigField "String", "GOAT_API_URL", "\"$GOAT_API_URL_LOCAL\""

			// DEBUG-only
			buildConfigField "Boolean", "AUTO_FILL_USER_ID", "false"
			buildConfigField "Boolean", "BYPASS_PRINTER", "false"
		}
	}

	publishing {
		singleVariant('devDebug') {
			publishApk()
		}

		singleVariant('stageDebug') {
			publishApk()
		}

		singleVariant('prodRelease') {
			publishApk()
		}
	}

	compileOptions {
		sourceCompatibility JavaVersion.VERSION_17
		targetCompatibility JavaVersion.VERSION_17
	}

	kotlinOptions {
		jvmTarget = JavaVersion.VERSION_17
	}

	buildFeatures {
		buildConfig true
		compose true
	}

	composeOptions {
		kotlinCompilerExtensionVersion '1.5.5'
	}

	packagingOptions {
		resources {
			excludes += '/META-INF/{AL2.0,LGPL2.1}'
		}
	}

	testOptions {
		unitTests {
			includeAndroidResources = true
		}
	}
}

dependencies {
	// AndroidX
	implementation 'androidx.core:core-ktx:1.13.1'
	testImplementation 'androidx.test.ext:junit:1.2.1'
	testImplementation 'androidx.test.espresso:espresso-core:3.6.1'
	androidTestImplementation 'androidx.test.ext:junit-ktx:1.2.1'

	// AndroidX - Compose - BOM
	def composeBom = platform('androidx.compose:compose-bom:2024.09.01')
	implementation composeBom
	testImplementation composeBom
	androidTestImplementation composeBom
	implementation 'androidx.compose.material3:material3'
	implementation 'androidx.compose.ui:ui-tooling-preview'
	implementation 'androidx.compose.foundation:foundation-android:1.7.1'
	implementation "androidx.compose.runtime:runtime-livedata"
	debugImplementation 'androidx.compose.ui:ui-tooling'
	debugImplementation 'androidx.compose.ui:ui-test-manifest'
	testImplementation 'androidx.compose.ui:ui-test-junit4'
	androidTestImplementation 'androidx.compose.ui:ui-test-junit4'

	// AndroidX - Compose - Integrations
	implementation 'androidx.activity:activity-compose:1.9.2'
	implementation 'androidx.navigation:navigation-compose:2.8.0'
	implementation 'androidx.lifecycle:lifecycle-runtime-compose:2.8.5'

	// Hilt
	implementation 'com.google.dagger:hilt-android:2.49'
	implementation 'androidx.hilt:hilt-navigation-compose:1.2.0'
	ksp 'com.google.dagger:hilt-compiler:2.48.1'

	// Retrofit
	implementation 'com.squareup.retrofit2:retrofit:2.9.0'
	implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
	implementation 'com.squareup.okhttp3:logging-interceptor:4.11.0'

	// Image Loading
	implementation 'io.coil-kt:coil-compose:2.4.0'

	// Microsoft Clarity
	//	implementation 'com.microsoft.clarity:clarity:1.3.2'

	// DataStore
	implementation "androidx.datastore:datastore-core:1.1.1"
	implementation "com.google.protobuf:protobuf-javalite:3.23.2"
	implementation "androidx.datastore:datastore-preferences:1.1.1"

	//noinspection GradleDependency - 1.13.4 breaks spying lambdas, this seems to be a library bug.
	testImplementation 'io.mockk:mockk:1.13.3'
	testImplementation 'junit:junit:4.13.2'
	testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.7.3'
	testImplementation 'org.robolectric:robolectric:4.11.1'

	//Image zooming
	implementation("net.engawapg.lib:zoomable:1.5.1")

	//Firebase Messaging
	implementation platform('com.google.firebase:firebase-bom:33.3.0')
	implementation 'com.google.firebase:firebase-database'
	implementation 'com.google.firebase:firebase-messaging'
}

afterEvaluate {
	publishing {
		repositories {
		}

		publications {
			def variantsToPublish = ['devDebug', 'stageDebug', 'prodRelease']

			android.applicationVariants.findAll { variant ->
				variantsToPublish.contains(variant.name)
			}.each { variant ->
				variant.outputs.each { output ->
					create(variant.name, MavenPublication) {
						groupId = 'com.nextuple.nsf'
						artifactId = "nsf-${variant.flavorName}"
						version = "$APK_VERSION-$GIT_HASH"

						artifact(output.outputFile)
					}
				}
			}
		}
	}
}

afterEvaluate {
	tasks.withType(PublishToMavenRepository).tap {
		configureEach { task ->
			def match = task.name =~ '^publish(.*)(Release|Debug)PublicationTo(.*)$'
			dependsOn("assemble${match[0][1]}${match[0][2]}")
		}
	}
}

protobuf {
	protoc {
		artifact = "com.google.protobuf:protoc:3.25.0"
	}
	generateProtoTasks {
		all().each { task ->
			task.builtins {
				java {
					option 'lite'

				}
			}
		}
	}
}

androidComponents {
	onVariants(selector().all()) { variant ->
		afterEvaluate {
			def protoTask =
					project.tasks.getByName("generate" + variant.name.substring(0, 1).toUpperCase() + variant.name.substring(1) + "Proto")

			project.tasks.getByName("ksp" + variant.name.substring(0, 1).toUpperCase() + variant.name.substring(1) + "Kotlin") {
				dependsOn(protoTask)
				setSource(
						protoTask.outputBaseDir
				)
			}
		}
	}
}

sourceSets {
	main {
		java {
			include 'src/main/proto/**'
		}
	}
}
